# Navigation Links

#[[main]]
  #name = "Posts"
  #url = "landing/"
  #weight = 10

[[main]]
  name = "Videos"
  url = "video_landing/"
  weight = 20
  
#[[main]]
  #name = "Meet the Team"
  #url = "#people"
  #weight = 30
  
[[main]]
  name = "Coding Playlist"
  url = "https://open.spotify.com/playlist/7AYUKJwDYLbKO4LYWcnscF?si=re3FM6LSRT6udGMF2HQ81g"
  weight = 20

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40
  
[[main]]
  name = "Resume"
  url = "files/resume.pdf"
  weight = 60
  
  
  [[main]]
  name = "Code Portfolio"
  url = "#projects"
  weight = 80

