# Navigation Links

#[[main]]
  #name = "Posts"
  #url = "landing/"
  #weight = 10

[[main]]
  name = "Videos"
  url = "video_landing/"
  weight = 20
  
#[[main]]
  #name = "Meet the Team"
  #url = "#people"
  #weight = 30

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40
  
[[main]]
  name = "Resume"
  url = "files/resume.pdf"
  weight = 60
  

